# Generated by Django 5.1 on 2024-08-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '__first__'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.componentmodel')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
            ],
        ),
    ]
